# Generated by Django 2.1.3 on 2018-11-03 08:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FreePost',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('publisehd_date', models.DateTimeField(auto_now_add=True)),
                ('content', models.TextField()),
                ('last_edit_date', models.DateTimeField(auto_now=True)),
                ('number_of_edits', models.IntegerField(blank=True, default=0, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='uploads/%Y/%m/%d/orig')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='NoticePost',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('publisehd_date', models.DateTimeField(auto_now_add=True)),
                ('content', models.TextField()),
                ('last_edit_date', models.DateTimeField(auto_now=True)),
                ('number_of_edits', models.IntegerField(blank=True, default=0, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='uploads/%Y/%m/%d/orig')),
                ('notice_type', models.IntegerField(choices=[(1, '상단고정'), (0, '고정하지 않음')])),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ProposalPost',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('publisehd_date', models.DateTimeField(auto_now_add=True)),
                ('content', models.TextField()),
                ('last_edit_date', models.DateTimeField(auto_now=True)),
                ('number_of_edits', models.IntegerField(blank=True, default=0, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='uploads/%Y/%m/%d/orig')),
                ('proposal_type', models.CharField(choices=[('PP', '건의'), ('PS', '신고')], max_length=2)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ReportPost',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('publisehd_date', models.DateTimeField(auto_now_add=True)),
                ('content', models.TextField()),
                ('last_edit_date', models.DateTimeField(auto_now=True)),
                ('number_of_edits', models.IntegerField(blank=True, default=0, null=True)),
                ('area', models.CharField(choices=[('SE', '서울'), ('IC', '인천'), ('GG', '경기'), ('DJ', '대전'), ('SJ', '세종'), ('CB', '충북'), ('CN', '충남'), ('GW', '강원'), ('GJ', '광주'), ('JB', '전북'), ('JN', '전남'), ('BS', '부산'), ('DG', '대구'), ('US', '울산'), ('GB', '경북'), ('GN', '경남'), ('JJ', '제주')], max_length=2)),
                ('specific_area', models.CharField(max_length=200)),
                ('image', models.ImageField(upload_to='uploads/%Y/%m/%d/orig')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
