# Generated by Django 2.1.3 on 2018-11-03 09:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='freepost',
            name='number_of_edits',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='noticepost',
            name='number_of_edits',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='proposalpost',
            name='number_of_edits',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='reportpost',
            name='number_of_edits',
            field=models.IntegerField(blank=True, default=0),
        ),
    ]
