# Generated by Django 2.1.3 on 2018-11-05 09:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0002_auto_20181103_1852'),
    ]

    operations = [
        migrations.RenameField(
            model_name='freepost',
            old_name='publisehd_date',
            new_name='published_date',
        ),
        migrations.RenameField(
            model_name='noticepost',
            old_name='publisehd_date',
            new_name='published_date',
        ),
        migrations.RenameField(
            model_name='proposalpost',
            old_name='publisehd_date',
            new_name='published_date',
        ),
        migrations.RenameField(
            model_name='reportpost',
            old_name='publisehd_date',
            new_name='published_date',
        ),
    ]
