# Generated by Django 2.1.3 on 2018-11-07 06:30

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('board', '0006_auto_20181105_2104'),
    ]

    operations = [
        migrations.AddField(
            model_name='freecomment',
            name='hates',
            field=models.ManyToManyField(related_name='freecomment_hates', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='freecomment',
            name='likes',
            field=models.ManyToManyField(related_name='freecomment_likes', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='freepost',
            name='hates',
            field=models.ManyToManyField(related_name='freepost_hates', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='freepost',
            name='likes',
            field=models.ManyToManyField(related_name='freepost_likes', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='noticecomment',
            name='hates',
            field=models.ManyToManyField(related_name='noticecomment_hates', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='noticecomment',
            name='likes',
            field=models.ManyToManyField(related_name='noticecomment_likes', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='noticepost',
            name='hates',
            field=models.ManyToManyField(related_name='noticepost_hates', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='noticepost',
            name='likes',
            field=models.ManyToManyField(related_name='noticepost_likes', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='proposalcomment',
            name='hates',
            field=models.ManyToManyField(related_name='proposalcomment_hates', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='proposalcomment',
            name='likes',
            field=models.ManyToManyField(related_name='proposalcomment_likes', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='proposalpost',
            name='hates',
            field=models.ManyToManyField(related_name='proposalpost_hates', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='proposalpost',
            name='likes',
            field=models.ManyToManyField(related_name='proposalpost_likes', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='reportcomment',
            name='hates',
            field=models.ManyToManyField(related_name='reportcomment_hates', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='reportcomment',
            name='likes',
            field=models.ManyToManyField(related_name='reportcomment_likes', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='reportpost',
            name='hates',
            field=models.ManyToManyField(related_name='reportpost_hates', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='reportpost',
            name='likes',
            field=models.ManyToManyField(related_name='reportpost_likes', to=settings.AUTH_USER_MODEL),
        ),
    ]
