# Generated by Django 2.1.3 on 2018-11-12 05:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0008_auto_20181110_1810'),
    ]

    operations = [
        migrations.AlterField(
            model_name='freecomment',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='%Y/%m/%d/orig'),
        ),
        migrations.AlterField(
            model_name='freepost',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='%Y/%m/%d/orig'),
        ),
        migrations.AlterField(
            model_name='noticecomment',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='%Y/%m/%d/orig'),
        ),
        migrations.AlterField(
            model_name='noticepost',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='%Y/%m/%d/orig'),
        ),
        migrations.AlterField(
            model_name='proposalcomment',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='%Y/%m/%d/orig'),
        ),
        migrations.AlterField(
            model_name='proposalpost',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='%Y/%m/%d/orig'),
        ),
        migrations.AlterField(
            model_name='reportcomment',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='%Y/%m/%d/orig'),
        ),
    ]
