# Generated by Django 2.1.3 on 2018-11-12 05:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0009_auto_20181112_1430'),
    ]

    operations = [
        migrations.AlterField(
            model_name='freepost',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='free/%Y/%m/%d/orig'),
        ),
        migrations.AlterField(
            model_name='noticepost',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='notice/%Y/%m/%d/orig'),
        ),
        migrations.AlterField(
            model_name='proposalpost',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='proposal/%Y/%m/%d/orig'),
        ),
        migrations.AlterField(
            model_name='reportpost',
            name='image',
            field=models.ImageField(upload_to='report/%Y/%m/%d/orig'),
        ),
    ]
