# Generated by Django 2.1.3 on 2018-11-15 06:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0012_auto_20181115_1534'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='freecomment',
            name='published_date_only',
        ),
        migrations.RemoveField(
            model_name='freepost',
            name='published_date_only',
        ),
        migrations.RemoveField(
            model_name='noticecomment',
            name='published_date_only',
        ),
        migrations.RemoveField(
            model_name='noticepost',
            name='published_date_only',
        ),
        migrations.RemoveField(
            model_name='proposalcomment',
            name='published_date_only',
        ),
        migrations.RemoveField(
            model_name='proposalpost',
            name='published_date_only',
        ),
        migrations.RemoveField(
            model_name='reportcomment',
            name='published_date_only',
        ),
        migrations.RemoveField(
            model_name='reportpost',
            name='published_date_only',
        ),
    ]
