# Generated by Django 2.1.3 on 2018-11-20 07:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0013_auto_20181115_1540'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reportpost',
            name='specific_area',
            field=models.CharField(max_length=20),
        ),
    ]
