# Generated by Django 2.1.3 on 2018-11-30 11:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0016_freeimages_noticeimages_proposalimages_reportimages'),
    ]

    operations = [
        migrations.AlterField(
            model_name='freeimages',
            name='post',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='images', to='board.FreePost'),
        ),
        migrations.AlterField(
            model_name='noticeimages',
            name='post',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='images', to='board.NoticePost'),
        ),
        migrations.AlterField(
            model_name='proposalimages',
            name='post',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='images', to='board.ProposalPost'),
        ),
        migrations.AlterField(
            model_name='reportimages',
            name='post',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='images', to='board.ReportPost'),
        ),
    ]
