# Generated by Django 2.1.3 on 2018-12-01 06:07

import board.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0018_auto_20181130_2109'),
    ]

    operations = [
        migrations.AlterField(
            model_name='freecomment',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=board.models.user_directory_path),
        ),
        migrations.AlterField(
            model_name='freeimages',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=board.models.user_directory_path, verbose_name='Image'),
        ),
        migrations.AlterField(
            model_name='noticecomment',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=board.models.user_directory_path),
        ),
        migrations.AlterField(
            model_name='noticeimages',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=board.models.user_directory_path, verbose_name='Image'),
        ),
        migrations.AlterField(
            model_name='noticepost',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=board.models.user_directory_path),
        ),
        migrations.AlterField(
            model_name='proposalcomment',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=board.models.user_directory_path),
        ),
        migrations.AlterField(
            model_name='proposalimages',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=board.models.user_directory_path, verbose_name='Image'),
        ),
        migrations.AlterField(
            model_name='proposalpost',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=board.models.user_directory_path),
        ),
        migrations.AlterField(
            model_name='reportcomment',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=board.models.user_directory_path),
        ),
        migrations.AlterField(
            model_name='reportimages',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=board.models.user_directory_path, verbose_name='Image'),
        ),
        migrations.AlterField(
            model_name='reportpost',
            name='image',
            field=models.ImageField(upload_to=board.models.user_directory_path),
        ),
    ]
