# Generated by Django 2.1.3 on 2018-12-03 09:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('board', '0019_auto_20181201_1507'),
    ]

    operations = [
        migrations.CreateModel(
            name='Nickname',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nickname', models.CharField(max_length=20, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.RemoveField(
            model_name='freecomment',
            name='author_nickname',
        ),
        migrations.RemoveField(
            model_name='freepost',
            name='author_nickname',
        ),
        migrations.RemoveField(
            model_name='noticecomment',
            name='author_nickname',
        ),
        migrations.RemoveField(
            model_name='noticepost',
            name='author_nickname',
        ),
        migrations.RemoveField(
            model_name='proposalcomment',
            name='author_nickname',
        ),
        migrations.RemoveField(
            model_name='proposalpost',
            name='author_nickname',
        ),
        migrations.RemoveField(
            model_name='reportcomment',
            name='author_nickname',
        ),
        migrations.RemoveField(
            model_name='reportpost',
            name='author_nickname',
        ),
        migrations.AlterField(
            model_name='freepost',
            name='title',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='noticepost',
            name='title',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='proposalpost',
            name='title',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='reportpost',
            name='specific_area',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='reportpost',
            name='title',
            field=models.CharField(max_length=50),
        ),
    ]
