# Generated by Django 2.1.3 on 2018-12-03 10:23

import board.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0021_auto_20181203_1844'),
    ]

    operations = [
        migrations.AlterField(
            model_name='freecomment',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=board.models.user_directory_path_first),
        ),
        migrations.AlterField(
            model_name='freepost',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=board.models.user_directory_path_first),
        ),
        migrations.AlterField(
            model_name='noticecomment',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=board.models.user_directory_path_first),
        ),
        migrations.AlterField(
            model_name='noticepost',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=board.models.user_directory_path_first),
        ),
        migrations.AlterField(
            model_name='proposalcomment',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=board.models.user_directory_path_first),
        ),
        migrations.AlterField(
            model_name='proposalpost',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=board.models.user_directory_path_first),
        ),
        migrations.AlterField(
            model_name='reportcomment',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=board.models.user_directory_path_first),
        ),
        migrations.AlterField(
            model_name='reportpost',
            name='image',
            field=models.ImageField(null=True, upload_to=board.models.user_directory_path_first),
        ),
    ]
