# Generated by Django 2.1.3 on 2018-12-04 12:35

import django.contrib.auth.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0022_auto_20181203_1923'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nickname',
            name='nickname',
            field=models.CharField(error_messages={'unique': '이미 존재하는 닉네임입니다.'}, help_text='필수입니다. 30자 이하의 문자, 숫자, @/./+/-/_ 의 조합이어야 합니다.', max_length=30, null=True, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()]),
        ),
    ]
